[theme]
primaryColor = "#259DFF"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1B1B1B"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
